#!/usr/bin/env bash

#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=5M
#SBATCH --time=20:00:00
#SBATCH --job-name=trimmomatic
#SBATCH --mail-user=zhihui.wang@students.unibe.ch
#SBATCH --mail-type=begin,end

module add UHTS/Quality_control/fastp/0.19.5
cd /data/courses/rnaseq/breastcancer_de/zwang_workspace/trim
for i in `du -sh /data/courses/rnaseq/breastcancer_de/reads/* | cut -d '/' -f7 | cut -d '.' -f1 | cut -d '_' -f1 | sort | uniq`
do
fastp -i /data/courses/rnaseq/breastcancer_de/reads/${i}_R1.fastq.gz -I /data/courses/rnaseq/breastcancer_de/reads/${i}_R2.fastq.gz -o ${i}_R1.fastq.gz -O ${i}_R2.fastq.gz

done
