#!/usr/bin/env bash

#SBATCH --cpus-per-task=20
#SBATCH --mem-per-cpu=5G
#SBATCH --time=20:00:00
#SBATCH --job-name=trimmomatic
#SBATCH --mail-user=zhihui.wang@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --output=/home/zwang/trimmomatic_output_mapping_%j.o
#SBATCH --error=/home/zwang/trimmomatic_error_mapping_%j.e

module add UHTS/Analysis/trimmomatic/0.36
cd /data/courses/rnaseq/breastcancer_de/zwang_workspace/trim
for i in `du -sh /data/courses/rnaseq/breastcancer_de/reads/* | cut -d '/' -f7 | cut -d '.' -f1 | cut -d '_' -f1 | sort | uniq`

do 

java -jar trimmomatic-0.36.jar PE -threads 20 -phred33 /data/courses/rnaseq/breastcancer_de/reads/${i}_R1.fastq.gz /data/courses/rnaseq/breastcancer_de/reads/${i}_R2.fastq.gz ${i}1.clean.fastq ${i}1.unpaired.fastq ${i}2.clean.fastq ${i}2.unpaired.fastq ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

done
