#!/usr/bin/env bash

#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=10000M
#SBATCH --time=15:00:00
#SBATCH --job-name=mapping
#SBATCH --mail-user=zhihui.wang@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --output=/home/zwang/output_mapping_%j.o
#SBATCH --error=/home/zwang/error_mapping_%j.e


module add UHTS/Analysis/samtools/1.10
hisat2 -q -p 4 -x hg38 -1 reads1 -2 reads2 -S out.sam
#-q input file is fastq
echo "start! \n"
for reads in `du -sh /data/courses/rnaseq/breastcancer_de/reads/* | cut -d '/' -f2 `
do
#create the file
mkdir /home/zwang/RNA_Other/mapping/${reads}
#hisat mapping
hisat2 -q -p 4 -x hg38 -1 /data/courses/rnaseq/breastcancer_de/reads/${reads}/${reads}_R1.fastq.gz -2 /data/courses/rnaseq/breastcancer_de/reads/${reads}/${reads}_R2.fastq.gz -S /home/zwang/RNA_Other/mapping/${reads}/${sample}out.sam > /home/zwang/RNA_Other/mapping/${reads}/${sample}align.log 2>&1
###convert sam to bam
samtools view -b /home/zwang/RNA_Other/mapping/${reads}/${sample}out.sam > /home/zwang/RNA_Other/mapping/${reads}/${sample}out.bam
##samfiles sorting
 samtools sort -@ 4 -o /home/zwang/RNA_Other/mapping/${reads}/${sample}out.bam /home/zwang/RNA_Other/mapping/${reads}/${sample}out_sorted.bam###continue
 
##index bam files
samtools index  /home/zwang/RNA_Other/mapping/${reads}/${sample}out_sorted.bam

done
